apiVersion: apps/v1
kind: Deployment
metadata:
  name: vpc-microservice-deployment
  namespace: vpc-microservice
  labels:
    app: vpc-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vpc-microservice
  template:
    metadata:
      labels:
        app: vpc-microservice
    spec:
      containers:
      - name: vpc-microservice
        image: vpc-microservice:latest
        imagePullPolicy: Never
        command: ["python3", "main.py"]
        env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: aws-creds-secret
                key: aws_access_key_id
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: aws-creds-secret
                key: aws_secret_access_key
          - name: AWS_REGION
            valueFrom:
              secretKeyRef:
                name: aws-creds-secret
                key: aws_region
          - name: SQS_URL
            valueFrom:
              secretKeyRef:
                name: aws-creds-secret
                key: sqs_url
          - name: PULUMI_ACCESS_TOKEN
            valueFrom:
              secretKeyRef:
                name: aws-creds-secret
                key: pulumi_access_token
        ports:
          - containerPort: 8000
        resources:
          limits:
            cpu: "500m"  # Máximo 0.5 CPU
            memory: "512Mi"  # Máximo 512 MB de RAM
          requests:
            cpu: "250m"  # Requiere al menos 0.25 CPU
            memory: "256Mi"  # Requiere al menos 256 MB de RAM
