apiVersion: apps/v1
kind: Deployment
metadata:
  name: vpc-microservice-deployment
  labels:
    app: vpc-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vpc-microservice
  template:
    metadata:
      labels:
        app: vpc-microservice
    spec:
      containers:
      - name: vpc-microservice
        image: jcarloslopez2/vpc-microservice:latest
        command: ["python3", "main.py"]
        env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: aws-creds-secret
                key: aws_access_key_id
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: aws-creds-secret
                key: aws_secret_access_key
          - name: AWS_REGION
            value: "us-east-1"
          - name: SQS_URL
            value: "https://sqs.us-east-1.amazonaws.com/160885293398/vpcQueue-02796a8"
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "250m"
            memory: "256Mi"
